use macros::lyric_chop;

const GENERIC_QUOTES: &[&str] = &[
	// 10 character limit.
	"Im a creep",
	"a wirdough",
	"uwu"		,
	"owo"		,
	"awa"		,
	"nya"		,
	"uwu"		,
	"owo"		,
	"awa"		,
	"nya"		,
	"uwu"		,
	"owo"		,
	"uwu"		,
	"owo"		,
	"uwu"		,
	"owo"		,
	"Death eggs",
	"are wet"	,
	"bungo"		,
	"bongo"		,
	"bingo"		,
	"Hello!"	,
	"Hi there!"	,
	"Howdy!"	,
	"Greetings!",
	"Howdy doo!",
	"Hey!"		,
	"Listen!"	,
	"Watch out!",
	"Behind you",
	"Boo!"		,
	"Dark days"	,
	"Roll bluff",
	"Hyaah!"	,
	"Your mom!"	,
	"Nyeh hehe!",
	"Thriller"	,
	"In the end",
	"cabbeg"	,
	"cabag"		,
	"cabbege"	,
];

lyric_chop!(FUNERAL_RITES, r"Day is done, gone the sun, From the hills, from the lake, from the skies. All is well, safely rest, God is nigh. Go to sleep, peaceful sleep, may the soldier or sailor, God keep. On the land or the deep, Safe in sleep. Love, good night, must thou go, when the day, and the night need thee so? All is well. Speedeth all To their rest. Fades the light; And afar Goeth day, And the stars Shineth bright, Fare thee well; Day has gone, night is on. Thanks and praise, for our days, 'Neath the sun, Neath the stars, 'Neath the sky, As we go, this we know, God is nigh.");
